import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Award, BadgeCheck, CalendarDays, MapPin, Sparkles, Users } from "lucide-react";
import { event, isConfirmedText, isPaymentRegistrationAvailable, type ConfirmationState } from "@/config/event";
import { calculateProductionPricing } from "@/lib/payment-pricing";
import { confirmedBenefits } from "@/content/landing";
import { Faq } from "@/components/landing/Faq";
import { CinematicHero } from "@/components/landing/CinematicHero";
import { IgnitionThread } from "@/components/landing/IgnitionThread";
import { LandingHeader } from "@/components/landing/LandingHeader";
import { SitePreloader } from "@/components/landing/SitePreloader";
import { WorkshopJourney } from "@/components/landing/WorkshopJourney";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { SiteFooter } from "@/components/SiteFooter";

const detail = (fact: { value: string | null; confirmation: ConfirmationState }) => isConfirmedText(fact) ? fact.value : "To be announced";

export default function Home() {
  const registrationAvailable = isPaymentRegistrationAvailable();
  const cta = registrationAvailable ? { href: "/register", label: "Register Now" } : { href: "#details", label: "View event details" };
  const pricing = calculateProductionPricing({ registrationOpenAt: event.registration.registrationOpenAt, earlyBirdDurationHours: event.fee.pricing.earlyBirdDurationHours, earlyBirdAmount: event.fee.pricing.earlyBirdAmount, regularAmount: event.fee.pricing.regularAmount });
  const pricingCopy = <>Early Bird ₹{event.fee.pricing.earlyBirdAmount} <span aria-hidden>·</span> Regular ₹{event.fee.pricing.regularAmount}</>;
  return <div id="top" className="landing-shell"><SitePreloader /><LandingHeader /><main>
    <CinematicHero />
    <section className="landing-association" aria-label="Event association"><Container><div className="association-lockup association-lockup--branded"><div className="association-lockup__logos"><Image unoptimized src="/images/logo2.png" alt="Illuminate 2026 official logo" width={188} height={68} className="association-lockup__illuminate" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/ecell-logo.png" alt="E-Cell MET logo" width={72} height={72} className="association-lockup__met" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/e-cell-iitb.png" alt="E-Cell IIT Bombay logo" width={54} height={62} className="association-lockup__iitb" /></div><div className="association-lockup__details"><span className="association-lockup__eyebrow">Official association</span><strong className="association-lockup__title">An E-Cell IIT Bombay initiative, hosted by {event.organizer.name}</strong><p>{event.association.label} · Illuminate {event.identity.edition}</p></div></div></Container></section>
    <section id="about" className="landing-section landing-why"><Container><SectionHeading eyebrow="About Illuminate" title="A 6-hour entrepreneurship workshop experience."><p>{event.identity.shortDescription} Hosted by {event.organizer.name}, associated with the Illuminate initiative of E-Cell IIT Bombay.</p></SectionHeading><div className="why-composition"><p className="why-composition__lead">IIT Bombay&apos;s entrepreneurship ecosystem, brought to your campus.</p><div className="why-network" aria-hidden><span>?</span><span>?</span><span>?</span><span className="why-network__core">+</span><IgnitionThread /></div><div className="why-composition__points"><span>Ideas</span><span>Perspective</span><span>Momentum</span></div></div></Container></section>
    <section id="journey" className="landing-section landing-journey"><Container><SectionHeading className="journey-intro" eyebrow="Workshop highlights · 6 hours" title="From a spark of interest to a clearer next move."><p>A 6-hour interactive flow. Session titles describe intent — detailed timings will be announced with the schedule.</p></SectionHeading><WorkshopJourney /></Container></section>
    <section className="landing-section landing-value"><Container><div className="value-grid"><div><p className="text-eyebrow">Why attend</p><h2 className="text-section-title">Make curiosity more useful.</h2></div><div className="value-grid__body"><p>Illuminate is open to everyone who wants an intentional entry point into entrepreneurship — not a list of promises, but a setting to explore what matters to them.</p><ul className="value-grid__takeaways"><li><Users aria-hidden /> Hands-on 6-hour workshop, not a passive talk</li><li><BadgeCheck aria-hidden /> Structured feedback from mentors and peers</li><li><Award aria-hidden /> Certificate path via E-Cell IIT Bombay initiative</li></ul><div className="value-grid__rule" /><p className="text-text-muted">Early Bird applies during the first 5 days of registration.</p></div><div className="value-map" aria-label="Registration pricing"><span className="value-map__dimension value-map__dimension--question">Early Bird</span><span className="value-map__dimension value-map__dimension--context">Regular</span><div className="value-map__core"><span>{pricing.tier === "early_bird" ? "Early Bird active" : "Registration"}</span><strong>₹{pricing.amount.toLocaleString("en-IN")}</strong></div><span className="value-map__dimension value-map__dimension--exchange">₹{event.fee.pricing.earlyBirdAmount}</span><span className="value-map__dimension value-map__dimension--direction">₹{event.fee.pricing.regularAmount}</span></div></div></Container></section>
    {confirmedBenefits.length ? <section className="landing-section landing-benefits"><Container><SectionHeading eyebrow="Confirmed inclusions" title="Part of your experience." /><ul>{confirmedBenefits.map((benefit) => <li key={benefit.key}><Sparkles aria-hidden /><div><h3>{benefit.label}</h3><p>{benefit.copy}</p></div></li>)}</ul></Container></section> : null}
    <section id="iitb" className="landing-section landing-iitb"><Container><div className="iitb-panel"><div className="iitb-panel__logos"><Image unoptimized src="/images/logo2.png" alt="Illuminate 2026 logo" width={188} height={68} className="iitb-panel__illuminate" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/ecell-logo.png" alt="E-Cell MET logo" width={72} height={72} className="iitb-panel__met" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/e-cell-iitb.png" alt="E-Cell IIT Bombay logo" width={54} height={62} className="iitb-panel__iitb" /></div><div><p className="text-eyebrow">E-Cell IIT Bombay</p><h2>Backed by India&apos;s leading student entrepreneurship ecosystem.</h2><p>Illuminate is an initiative of E-Cell IIT Bombay, hosted at MET by {event.organizer.name}. Certificate and opportunity details are published here only once confirmed.</p><ul className="iitb-panel__points"><li>Illuminate initiative of E-Cell IIT Bombay</li><li>Certificate path — to be announced</li><li>E-Summit and ecosystem exposure — to be announced</li></ul></div></div></Container></section>
    <section id="details" className="landing-section landing-details"><Container><div className="event-object"><div className="event-object__identity"><span>ILL / {event.identity.edition}</span><strong>{event.identity.name}</strong><small>E-Cell IIT Bombay × {event.organizer.name}</small></div><div className="event-object__facts"><div><span className="event-object__label"><CalendarDays aria-hidden /> Schedule</span><strong>{detail(event.schedule.date)}</strong></div><div><span className="event-object__label"><MapPin aria-hidden /> Venue</span><strong>{detail(event.schedule.venue)}</strong></div><div><span className="event-object__label">Registration</span><strong>{registrationAvailable ? "Open" : "Opening soon"}</strong></div><div><span className="event-object__label">Pricing</span><strong>{pricingCopy}</strong></div></div><div className="event-object__note">Registration deadline: {detail(event.registration.deadline)}. Open to everyone — any college, branch, or year.</div></div></Container></section>
    <section id="faq" className="landing-section landing-faq"><Container><div className="landing-section__split"><SectionHeading eyebrow="Questions, answered" title="Clear before you commit."><p>Fee, eligibility, certificate, venue, timing, refund and payment queries.</p></SectionHeading><Faq /></div></Container></section>
    <section id="contact" className="landing-section landing-support"><Container><div className="support-panel"><div><p className="text-eyebrow">Contact us</p><h2>{event.organizer.name}</h2><p>For registration or payment support, contact {event.contacts.organizer.value} at <a className="underline" href={`mailto:${event.contacts.support.value}`}>{event.contacts.support.value}</a>.</p></div><p>{event.association.label}. Social links will appear here once confirmed.</p></div></Container></section>
    <section className="landing-final"><Container><div className="landing-final__inner"><IgnitionThread variant="converge" /><p className="text-eyebrow">Illuminate {event.identity.edition}</p><h2>Stay close to the spark.</h2><p>Registration is open to everyone. {pricingCopy}.</p><Link href={cta.href} className="landing-button"><span>Register Now</span><ArrowUpRight aria-hidden /></Link></div></Container></section>
  </main><SiteFooter />{!registrationAvailable ? <a className="landing-mobile-cta" href="#details">Registration opening soon <ArrowDownRight aria-hidden /></a> : <Link className="landing-mobile-cta" href="/register">Register Now <ArrowUpRight aria-hidden /></Link>}</div>;
}
