import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Award, BadgeCheck, CalendarDays, Compass, Lightbulb, MapPin, Mic, Sparkles, Users, Zap } from "lucide-react";
import { event, isConfirmedText, isPaymentRegistrationAvailable, type ConfirmationState } from "@/config/event";
import { calculateProductionPricing } from "@/lib/payment-pricing";
import { confirmedBenefits } from "@/content/landing";
import { Faq } from "@/components/landing/Faq";
import { Reveal } from "@/components/Reveal";
import { CinematicHero } from "@/components/landing/CinematicHero";
import { IgnitionThread } from "@/components/landing/IgnitionThread";
import { LandingHeader } from "@/components/landing/LandingHeader";
import { SitePreloader } from "@/components/landing/SitePreloader";
import { WorkshopJourney } from "@/components/landing/WorkshopJourney";
import { Container } from "@/components/ui/Container";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { SiteFooter } from "@/components/SiteFooter";

const detail = (fact: { value: string | null; confirmation: ConfirmationState }) => isConfirmedText(fact) ? fact.value : "To be announced";

export default function Home() {
  const registrationAvailable = isPaymentRegistrationAvailable();
  const cta = registrationAvailable ? { href: "/register", label: "Register Now" } : { href: "#details", label: "View event details" };
  const pricing = calculateProductionPricing({ registrationOpenAt: event.registration.registrationOpenAt, earlyBirdDurationHours: event.fee.pricing.earlyBirdDurationHours, earlyBirdAmount: event.fee.pricing.earlyBirdAmount, regularAmount: event.fee.pricing.regularAmount });
  const pricingCopy = <>Early Bird ₹{event.fee.pricing.earlyBirdAmount} <span aria-hidden>·</span> Regular ₹{event.fee.pricing.regularAmount}</>;
  return <div id="top" className="landing-shell"><SitePreloader /><LandingHeader /><main>
    <CinematicHero />
    <section className="landing-association" aria-label="Event association"><Container><div className="association-lockup association-lockup--branded"><div className="association-lockup__logos"><Image unoptimized src="/images/logo2.png" alt="Illuminate 2026 official logo" width={188} height={68} className="association-lockup__illuminate" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/ecell-logo.png" alt="E-Cell MET logo" width={72} height={72} className="association-lockup__met" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/e-cell-iitb.png" alt="E-Cell IIT Bombay logo" width={54} height={62} className="association-lockup__iitb" /></div><div className="association-lockup__details"><span className="association-lockup__eyebrow">Official association</span><strong className="association-lockup__title">Associated with the Illuminate initiative of E-Cell IIT Bombay, hosted by {event.organizer.name}</strong><p>{event.association.label} · Illuminate {event.identity.edition}</p></div></div></Container></section>
    <section id="about" className="landing-section landing-why"><Container><SectionHeading eyebrow="About Illuminate" title="An entrepreneurship workshop experience."><p>Not a passive talk — hands-on sessions and conversations, built for beginners and open to every college, branch, and year. Hosted by {event.organizer.name}, associated with the Illuminate initiative of E-Cell IIT Bombay.</p></SectionHeading><Reveal doorway className="why-composition"><p className="why-composition__lead">IIT Bombay&apos;s <em>entrepreneurship ecosystem</em>, brought to your campus.</p><div className="why-network" aria-hidden><span><Lightbulb aria-hidden /></span><span><Compass aria-hidden /></span><span><Zap aria-hidden /></span><span className="why-network__core">+</span><IgnitionThread /></div><div className="why-composition__points"><span>Ideas</span><span>Perspective</span><span>Momentum</span></div></Reveal><dl className="why-stats"><div><dt>Format</dt><dd>Interactive workshop</dd></div><div><dt>Entry from</dt><dd>₹{event.fee.pricing.earlyBirdAmount.toLocaleString("en-IN")}</dd></div><div><dt>Deadline</dt><dd>29 September 2026</dd></div><div><dt>Who can join</dt><dd>Everyone</dd></div></dl></Container></section><section id="speakers" className="landing-section landing-speakers"><Container><SectionHeading eyebrow="Speakers" title="The stage is being set."><p>The Illuminate speaker lineup is being locked in right now. Names appear here as soon as they&apos;re confirmed.</p></SectionHeading><Reveal doorway><div className="credential-frame speakers-frame"><div className="credential-frame__inner speakers-panel"><Mic aria-hidden className="speakers-mic" /><p className="speakers-live"><span className="speakers-pulse" aria-hidden />Announcing soon</p><p className="speakers-soon">The voices taking the stage are being confirmed.</p><p className="speakers-copy">Early Bird (₹599, first 120 hours) ends before Regular (₹699). Speaker names appear here once confirmed.</p><Link href="/register" className="landing-button"><span>Register Now</span><ArrowUpRight aria-hidden /></Link></div></div></Reveal></Container></section>
    <section id="journey" className="landing-section landing-journey"><Container><SectionHeading className="journey-intro" eyebrow="Workshop highlights" title="From a spark of interest to a clearer next move."><p>An interactive flow. Session titles describe intent — detailed timings will be announced with the schedule.</p></SectionHeading><Reveal doorway><WorkshopJourney /></Reveal></Container></section>
    <section className="landing-section landing-value"><Container><div className="value-grid"><div><p className="text-eyebrow">Pricing</p><h2 className="text-section-title">Simple, student pricing.</h2></div><div className="value-grid__body"><p>One flat fee. No hidden charges, no upsells.</p><ul className="value-grid__takeaways"><li><Users aria-hidden /> Hands-on workshop, not a passive talk</li><li><BadgeCheck aria-hidden /> Structured feedback from mentors and peers</li><li><Award aria-hidden /> Beginner-friendly, open to every college and branch</li></ul><div className="value-grid__rule" /><p className="text-text-muted">Early Bird applies during the first 120 hours (5 days) of registration.</p></div><div className="price-cards"><div className="price-card is-featured"><p className="price-card__tier">Early Bird{pricing.tier === "early_bird" ? <span className="price-card__badge">Active now</span> : null}</p><p className="price-card__amount">₹{event.fee.pricing.earlyBirdAmount.toLocaleString("en-IN")}</p><p className="price-card__note">For the first 120 hours (5 days) of registration. Lowest price for the same workshop.</p></div><div className="price-card"><p className="price-card__tier">Regular{pricing.tier === "regular" ? <span className="price-card__badge">Active now</span> : null}</p><p className="price-card__amount">₹{event.fee.pricing.regularAmount.toLocaleString("en-IN")}</p><p className="price-card__note">Standard entry, once Early Bird ends.</p></div></div><p className="price-cards__foot">Registration deadline: 29 September 2026 (exact closing time to be announced) · Open to everyone.</p></div></Container></section>
    {confirmedBenefits.length ? <section className="landing-section landing-benefits"><Container><SectionHeading eyebrow="Confirmed inclusions" title="Part of your experience." /><ul>{confirmedBenefits.map((benefit) => <li key={benefit.key}><Sparkles aria-hidden /><div><h3>{benefit.label}</h3><p>{benefit.copy}</p></div></li>)}</ul></Container></section> : null}
    <section id="iitb" className="landing-section landing-iitb"><Container><div className="iitb-panel"><div className="iitb-panel__logos"><Image unoptimized src="/images/logo2.png" alt="Illuminate 2026 logo" width={188} height={68} className="iitb-panel__illuminate" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/ecell-logo.png" alt="E-Cell MET logo" width={72} height={72} className="iitb-panel__met" /><span aria-hidden className="association-lockup__connector">×</span><Image unoptimized src="/images/e-cell-iitb.png" alt="E-Cell IIT Bombay logo" width={54} height={62} className="iitb-panel__iitb" /></div><div><p className="text-eyebrow">E-Cell IIT Bombay</p><h2>Backed by India&apos;s leading student entrepreneurship ecosystem.</h2><p>Illuminate is associated with the Illuminate initiative of E-Cell IIT Bombay, hosted at MET by {event.organizer.name}. Additional inclusions are published here only once confirmed.</p><ul className="iitb-panel__points"><li>Illuminate initiative of E-Cell IIT Bombay</li></ul></div></div></Container></section>
    <section id="details" className="landing-section landing-details"><Container><Reveal doorway><div className="event-object"><div className="event-object__identity"><span>ILL / {event.identity.edition}</span><Image unoptimized src="/images/logo2.png" alt="Illuminate 2026 official logo" width={376} height={137} className="event-object__logo" /><small>E-Cell IIT Bombay × {event.organizer.name}</small></div><div className="event-object__facts"><div><span className="event-object__label"><CalendarDays aria-hidden /> Schedule</span><strong>{detail(event.schedule.date)}</strong></div><div><span className="event-object__label"><MapPin aria-hidden /> Venue</span><strong>{detail(event.schedule.venue)}</strong></div><div><span className="event-object__label">Registration</span><strong>{registrationAvailable ? "Open" : "Opening soon"}</strong></div><div><span className="event-object__label">Pricing</span><strong>{pricingCopy}</strong></div></div><div className="event-object__note">Registration deadline: {detail(event.registration.deadline)}. Open to everyone — any college, branch, or year.</div></div></Reveal></Container></section>
    <section id="faq" className="landing-section landing-faq"><Container><div className="landing-section__split"><SectionHeading eyebrow="Questions, answered" title="Clear before you commit."><p>Fee, eligibility, certificate, venue, timing, refund and payment queries.</p></SectionHeading><Faq /></div></Container></section>
    <section id="contact" className="landing-section landing-support"><Container><div className="support-panel"><div><p className="text-eyebrow">Contact us</p><h2>{event.organizer.name}</h2><p>For registration or payment support, contact {event.contacts.organizer.value} at <a className="underline" href={`mailto:${event.contacts.support.value}`}>{event.contacts.support.value}</a>.</p></div><p>{event.association.label}. Social links will appear here once confirmed.</p></div></Container></section>
    <section className="landing-final"><Container><Reveal doorway><div className="landing-final__inner"><IgnitionThread variant="converge" /><p className="text-eyebrow">Illuminate {event.identity.edition}</p><h2>Stay close to the spark.</h2><p>Registration is open to everyone. {pricingCopy}.</p><Link href={cta.href} className="landing-button"><span>Register Now</span><ArrowUpRight aria-hidden /></Link></div></Reveal></Container></section>
  </main><SiteFooter /></div>;
}
