"use client";
/* eslint-disable @next/next/no-img-element -- authenticated proof requests must carry the session cookie. */

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Download, LogOut, Search, XCircle } from "lucide-react";

type Status = "payment_pending" | "submitted_for_verification" | "verified" | "rejected";
type Row = { publicId: string; isTest: boolean; participant: { fullName: string; email: string; phone: string }; payment: { snapshot: { expectedAmount: number | null }; status: Status; transactionReference?: string; currentProofId?: string; submittedAt?: string }; emailNotifications?: { paymentSubmitted?: { status: string }; paymentVerified?: { status: string } } };
type Dashboard = { rows: Row[]; total: number; realTotal: number; testRecords: number; metrics: Array<{ _id: Status; count: number; revenue: number }> };
const statusText: Record<Status, string> = { payment_pending: "Payment pending", submitted_for_verification: "Awaiting verification", verified: "Verified", rejected: "Rejected" };

export default function AdminPage() {
  const [password, setPassword] = useState(""); const [authed, setAuthed] = useState(false); const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(""); const [modalError, setModalError] = useState(""); const [loading, setLoading] = useState(false); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"" | Status>("submitted_for_verification"); const [scope, setScope] = useState<"" | "test" | "real">(""); const [selected, setSelected] = useState<Row | null>(null); const [confirmed, setConfirmed] = useState(false); const [reason, setReason] = useState(""); const [privateNote, setPrivateNote] = useState("");
  const fetchDashboard = useCallback(async (): Promise<Dashboard> => { const url = new URL("/api/admin/registrations", location.origin); if (query) url.searchParams.set("q", query); if (status) url.searchParams.set("status", status); if (scope) url.searchParams.set("scope", scope); const response = await fetch(url, { cache: "no-store" }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(json?.error?.message || "Could not refresh registrations."); return json.data as Dashboard; }, [query, scope, status]);
  const refresh = useCallback(async (): Promise<boolean> => { setLoading(true); try { setData(await fetchDashboard()); setAuthed(true); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not refresh registrations."); return false; } finally { setLoading(false); } }, [fetchDashboard]);
  useEffect(() => { const timer = setTimeout(() => void refresh(), 0); return () => clearTimeout(timer); }, [refresh]);
  const login = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/admin/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password }) }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(json?.error?.message || "Could not sign in."); setPassword(""); if (!await refresh()) throw new Error("Signed in, but the queue could not be refreshed."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not sign in."); } finally { setLoading(false); } };
  const review = async (action: "verify" | "reject") => { if (!selected) return; setLoading(true); setModalError(""); try { const body = action === "verify" ? selected.isTest ? { action, developmentSimulationVerified: confirmed } : { action, confirmedInRecipientAccount: confirmed } : { action, publicReason: reason, privateNote }; const response = await fetch(`/api/admin/registrations/${selected.publicId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json().catch(() => null); if (!response.ok) throw new Error(json?.error?.message || "Verification could not be saved. Refresh and try again."); const updated = await fetchDashboard(); setData(updated); setSelected(null); setConfirmed(false); setReason(""); setPrivateNote(""); } catch (cause) { setModalError(cause instanceof Error ? cause.message : "Verification could not be saved. Refresh and try again."); } finally { setLoading(false); } };
  if (!authed) return <main className="mx-auto max-w-md px-5 py-20"><p className="text-eyebrow text-brand-electric">Staff workspace</p><h1 className="mt-3 text-display">Admin sign in</h1><form className="mt-8 space-y-4 rounded-3xl border border-white/10 bg-white/[0.03] p-6" onSubmit={login}><label className="registration-field"><span>Password</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" required /></label>{error && <p role="alert" className="registration-field__error">{error}</p>}<button className="registration-primary-action w-full justify-center" disabled={loading}>Sign in</button></form></main>;
  const metric = (key: Status) => data?.metrics.find((item) => item._id === key)?.count ?? 0; const revenue = data?.metrics.reduce((sum, item) => sum + item.revenue, 0) ?? 0;
  return <main className="mx-auto max-w-7xl px-5 py-10"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-eyebrow text-brand-electric">Operations</p><h1 className="mt-2 text-display">Payment verification</h1><p className="mt-2 text-sm text-text-secondary">{data?.testRecords ? `${data.testRecords} development TEST record(s), excluded from real metrics and exports.` : "No development test records."}</p></div><div className="flex flex-wrap gap-3"><a className="registration-back" href="/api/admin/export"><Download aria-hidden /> IITB CSV</a><a className="registration-back" href="/api/admin/export?mode=internal"><Download aria-hidden /> Internal CSV</a><button className="registration-back" onClick={() => void fetch("/api/admin/auth/logout", { method: "POST" }).then(() => { setAuthed(false); setData(null); })}><LogOut aria-hidden /> Log out</button></div></header><section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric text="Real registrations" value={data?.realTotal ?? 0} />{(["payment_pending", "submitted_for_verification", "verified", "rejected"] as Status[]).map((key) => <Metric key={key} text={statusText[key]} value={metric(key)} />)}<Metric text="Verified revenue (real only)" value={`₹${revenue.toLocaleString("en-IN")}`} /></section><form className="mt-8 flex flex-col gap-3 sm:flex-row" onSubmit={(event) => { event.preventDefault(); void refresh(); }}><input className="min-h-11 flex-1 rounded-xl border border-white/15 bg-transparent px-4" placeholder="Reference, name, email, phone, or transaction reference" value={query} onChange={(event) => setQuery(event.target.value)} /><select className="min-h-11 rounded-xl border border-white/15 bg-ink px-4" value={status} onChange={(event) => setStatus(event.target.value as "" | Status)}><option value="">All statuses</option>{Object.entries(statusText).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select><select className="min-h-11 rounded-xl border border-white/15 bg-ink px-4" value={scope} onChange={(event) => setScope(event.target.value as "" | "test" | "real")}><option value="">All visible records</option><option value="test">TEST records</option><option value="real">Real records</option></select><button className="registration-primary-action"><Search aria-hidden /> Search</button></form>{error && <p role="alert" className="mt-4 registration-field__error">{error}</p>}<Queue rows={data?.rows ?? []} onSelect={(row) => { setModalError(""); setSelected(row); }} />{selected && <ReviewModal row={selected} confirmed={confirmed} setConfirmed={setConfirmed} reason={reason} setReason={setReason} privateNote={privateNote} setPrivateNote={setPrivateNote} error={modalError} loading={loading} onClose={() => setSelected(null)} onReview={review} />}</main>;
}
function Metric({ text, value }: { text: string; value: string | number }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs text-text-secondary">{text}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
function Badge() { return <span className="ml-2 rounded bg-amber-300/20 px-1.5 py-0.5 text-[10px] text-amber-100">TEST</span>; }
function Queue({ rows, onSelect }: { rows: Row[]; onSelect: (row: Row) => void }) { return <div className="mt-6 overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-white/10 text-xs text-text-secondary"><tr><th className="p-4">Reference</th><th className="p-4">Participant</th><th className="p-4">Expected</th><th className="p-4">Transaction</th><th className="p-4">Submitted</th><th className="p-4">Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.publicId} onClick={() => onSelect(row)} className="cursor-pointer border-b border-white/5 hover:bg-white/[0.03]"><td className="p-4 font-mono text-brand-electric">{row.publicId}{row.isTest && <Badge />}</td><td className="p-4"><p>{row.participant.fullName}</p><p className="text-xs text-text-secondary">{row.participant.email} · {row.participant.phone}</p></td><td className="p-4">{row.isTest ? "₹XXX · TEST" : `₹${row.payment.snapshot.expectedAmount}`}</td><td className="p-4 font-mono">{row.payment.transactionReference || "—"}</td><td className="p-4">{row.payment.submittedAt ? new Date(row.payment.submittedAt).toLocaleString("en-IN") : "—"}</td><td className="p-4">{row.isTest ? "TEST · " : ""}{statusText[row.payment.status]}</td></tr>)}{!rows.length && <tr><td colSpan={6} className="p-12 text-center text-text-secondary">No matching current-generation registrations.</td></tr>}</tbody></table></div>; }
function ReviewModal({ row, confirmed, setConfirmed, reason, setReason, privateNote, setPrivateNote, error, loading, onClose, onReview }: { row: Row; confirmed: boolean; setConfirmed: (value: boolean) => void; reason: string; setReason: (value: string) => void; privateNote: string; setPrivateNote: (value: string) => void; error: string; loading: boolean; onClose: () => void; onReview: (action: "verify" | "reject") => Promise<void> }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-4 backdrop-blur-sm"><section className="mx-auto my-8 max-w-3xl rounded-3xl border border-white/15 bg-ink p-6"><div className="flex justify-between"><div><p className="font-mono text-brand-electric">{row.publicId}{row.isTest && <Badge />}</p><h2 className="mt-1 text-2xl font-semibold">{row.participant.fullName}</h2></div><button className="registration-back" onClick={onClose}>Close</button></div><dl className="mt-6 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs text-text-secondary">Expected</dt><dd>{row.isTest ? "₹XXX · simulated" : `₹${row.payment.snapshot.expectedAmount}`}</dd></div><div><dt className="text-xs text-text-secondary">Transaction/reference</dt><dd className="font-mono">{row.payment.transactionReference}</dd></div></dl>{row.payment.currentProofId && <img src={`/api/admin/proof/${row.payment.currentProofId}`} alt={`Payment proof for ${row.publicId}`} className="mt-6 max-h-[520px] w-full rounded-2xl border border-white/15 object-contain" />}{row.payment.status === "submitted_for_verification" && <div className="mt-6 space-y-4 rounded-2xl border border-white/10 p-5"><label className="flex gap-3 text-sm"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span>{row.isTest ? "This verifies the simulated development workflow. No real bank or UPI payment was confirmed." : "I have confirmed payment in the authorized recipient account. A screenshot alone is not sufficient."}</span></label>{error && <p role="alert" className="registration-field__error">{error}</p>}<button disabled={!confirmed || loading} className="registration-primary-action" onClick={() => void onReview("verify")}><CheckCircle2 aria-hidden /> {row.isTest ? "Verify simulated test" : "Verify payment"}</button><label className="registration-field"><span>Participant-facing rejection reason</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} maxLength={300} /></label><label className="registration-field"><span>Private admin note</span><textarea value={privateNote} onChange={(event) => setPrivateNote(event.target.value)} maxLength={1000} /></label><button disabled={!reason.trim() || loading} className="registration-back border-red-400/40 text-red-200" onClick={() => void onReview("reject")}><XCircle aria-hidden /> Reject / request resubmission</button></div>}</section></div>; }
